/*
auto-generated by: https://github.com/react-spring/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useLoader } from 'react-three-fiber'
import { GLTFLoader, GLTF } from 'three/examples/jsm/loaders/GLTFLoader'

type GLTFResult = GLTF & {
  nodes: {
    Desk: THREE.Mesh
    Legs: THREE.Mesh
  }
  materials: {
    VertexColorMaterial: THREE.MeshStandardMaterial
  }
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useLoader<GLTFResult>(GLTFLoader, '/models/room-3d/room.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh material={materials.VertexColorMaterial} geometry={nodes.Desk.geometry} />
      <mesh material={materials.VertexColorMaterial} geometry={nodes.Legs.geometry} />
    </group>
  )
}
