/*
auto-generated by: https://github.com/react-spring/gltfjsx
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useLoader } from "react-three-fiber";
import { GLTFLoader, GLTF } from "three/examples/jsm/loaders/GLTFLoader";

type GLTFResult = GLTF & {
  nodes: {
    DeskSurface: THREE.Mesh;
    DeskLegs: THREE.Mesh;
    Laptop: THREE.Mesh;
  };
  materials: {
    VertexColorMaterial: THREE.MeshStandardMaterial;
  };
};

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const group = useRef<THREE.Group>();
  const { nodes, materials } = useLoader<GLTFResult>(
    GLTFLoader,
    "/models/room-3d/room.gltf"
  );
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        material={materials.VertexColorMaterial}
        geometry={nodes.DeskSurface.geometry}
      />
      <mesh
        material={materials.VertexColorMaterial}
        geometry={nodes.DeskLegs.geometry}
      />
      <mesh
        material={materials.VertexColorMaterial}
        geometry={nodes.Laptop.geometry}
        position={[0, 0.72, 0]}
      />
    </group>
  );
}
