/*
auto-generated by: https://github.com/react-spring/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useLoader } from 'react-three-fiber'
import { GLTFLoader, GLTF } from 'three/examples/jsm/loaders/GLTFLoader'

type GLTFResult = GLTF & {
  nodes: {
    Cube001: THREE.Mesh
  }
  materials: {}
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, } = useLoader<GLTFResult>(GLTFLoader, '/models/table-3d/scene.gltf')
  const material = new THREE.MeshStandardMaterial({
    roughness: 1.0,
    metalness: 0.0,
    vertexColors: true,
  });
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh material={material} geometry={nodes.Cube001.geometry} />
    </group>
  )
}
